internal/api/dataset.go
internal/api/job.go
internal/content/delete.go
internal/content/show.go
internal/jobs/operate.go

* id completion is now case insensitive
* content delete now has completion
* content delete will now require confirmation
* completion on operation and jobType flag under `jobs operate`

Improve completion

---

internal/api/entities.go
internal/docs/doc-transform.md
internal/queries/query_builder.go
internal/transform/test.go
internal/transform/transformator.go

Several functions has been improved upon, and will no longer crash.
Doc has been updated.
Also fixed a nil pointer when a query returned an empty row.

[FEATURE] Update and improve transform functions

---

CHANGELOG.md
internal/api/job.go
internal/docs/doc-jobs.md
internal/jobs/delete.go
internal/jobs/get.go
internal/jobs/history.go
internal/jobs/list.go
internal/jobs/operate.go
internal/jobs/status.go

add support for new job attributes:
title
tag
description

add support for new job attributes

---

internal/transform/test.go
internal/transform/transformator.go

ref https://github.com/mimiro-io/datahub/pull/97

add AsEntity transform helper to match datahub featureset

---

internal/web/token.go

Doing this to avoid instantiating a new client as the the client calls the getValidToken method via ResolveCredentials which causes the loop.

Move token refresh request out of client. Fixes #82

---

internal/command/datasets.go
internal/datasets/create.go

accompanies https://github.com/mimiro-io/datahub/pull/124

support proxy dataset creation

---

internal/api/query.go
internal/command/query.go
internal/queries/query_builder.go
internal/transform/transformator.go

add support for query in specific dataset

---

internal/jobs/list.go
internal/jobs/status.go
internal/utils/util.go

feature_113: refactor sorting on output list

---

internal/jobs/list.go
internal/jobs/status.go
internal/login/list.go
internal/utils/util.go

feature_115: fix sorting on mim login ls

---

internal/transform/transformator.go

 Add support for multiple log levels on transforms

---

internal/transform/export.go

feature_121: fix support for fetching transforms with id or title.

---

internal/jobs/add.go
internal/transform/import.go
internal/transform/importer.go
internal/transform/test.go
internal/utils/util.go

add support for typescript

---

.goreleaser.yml

Add rpm build to be used on red hat

Add rpm build

---

internal/command/query.go
internal/queries/query_builder.go
internal/transform/transformator.go

add --details to query, to match new flag in datahub API 

---

internal/transform/test.go

feature_144: add support for NewEntityFrom

---

internal/api/entities.go
internal/command/query.go

feature_165: add support for namespaces in mim query

---

internal/jobs/operate.go

This changes the default behavior for the run operation. Fixes #164

Add wait flag for job run operation

---

internal/jobs/list.go

Add restrictive filter matching & wildcard support

---

internal/login/list.go

No token for unsecured logins.

---

internal/login/logout.go

Token should be deleted on logout.

---

go.mod
internal/command/query.go
internal/queries/query_builder.go
internal/transform/importer.go
internal/web/web.go

Example usage:
```
mim query --file test-query.js
```

Add support for js file query. Fixes #177

---

internal/web/token.go

Missing fallthrough in switch cases.

---

.github/workflows/release.yml

To temporarily avoid deprecated functionality issue

Specify goreleaser version

---

internal/web/token.go

Add refresh token for login type admin
